CREATE TABLE IF NOT EXISTS albums (
  id SERIAL PRIMARY KEY,
  name TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS photos (
  id SERIAL PRIMARY KEY,
  album_id INTEGER NOT NULL REFERENCES albums(id) ON DELETE CASCADE,
  blob_url TEXT NOT NULL,
  filename TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE photos ADD COLUMN IF NOT EXISTS taken_at TIMESTAMPTZ;

ALTER TABLE albums ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE albums ADD COLUMN IF NOT EXISTS event_date DATE;
ALTER TABLE albums ADD COLUMN IF NOT EXISTS cover_photo_id INTEGER REFERENCES photos(id) ON DELETE SET NULL;
ALTER TABLE albums ADD COLUMN IF NOT EXISTS share_token TEXT UNIQUE;
ALTER TABLE photos ADD COLUMN IF NOT EXISTS caption TEXT;

CREATE TABLE IF NOT EXISTS login_attempts (
  id SERIAL PRIMARY KEY,
  ip TEXT NOT NULL,
  attempted_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS login_attempts_ip_time ON login_attempts (ip, attempted_at);
